# Generated by Django 3.2.3 on 2021-05-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_books_cathome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
