# Generated by Django 3.2.3 on 2021-05-14 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_seller_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
