# Generated by Django 3.2.3 on 2021-05-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210514_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('bookName', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('Review', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='cathome',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
