# Generated by Django 3.2.3 on 2021-05-14 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210514_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Review',
            new_name='desc',
        ),
    ]
