# Generated by Django 3.2.3 on 2021-05-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_review_review_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
