# Generated by Django 3.2.3 on 2021-05-14 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210515_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='pdf',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='seller',
            name='pdf',
            field=models.FileField(null=True, upload_to='pdf'),
        ),
    ]
