# Generated by Django 3.2.3 on 2021-05-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_customer_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
