# Generated by Django 3.2.3 on 2021-05-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_books_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf'),
        ),
    ]
