# Generated by Django 3.2.3 on 2021-05-21 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_seller_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
