# Generated by Django 3.2.3 on 2021-05-22 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20210522_2321'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
