# Generated by Django 3.2.3 on 2021-05-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_auto_20210524_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='anyfile',
            field=models.FileField(blank=True, null=True, upload_to='contact'),
        ),
    ]
