# Generated by Django 3.2.3 on 2021-05-26 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_alter_contact_anyfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='anyfile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
